### ISSUE TITLE
URL rewrite implementation

### ISSUE THREAD

**Issue by mahnouman** [filetrust/k8-reverse-proxy#12]
Think of a reverse proxy for a website of (http://www.xyz.com) , we need the reverse proxy to rewrite the URL of the main page plus the embedded objects, so if a user typed http://www.xyz.com.somedomain.com, he/she will hit the reverse proxy and the content will be retrieved from http://www.xyz.com.

A similar objective is mentioned in this serverfault question:
https://serverfault.com/questions/330401/how-do-i-rewrite-example-com-to-www-example-com

We need to original URL (http://www.xyz.com) plus the user facing one (http://www.xyz.com.somedomain.com) to be configurable and not hardcoded.

**Comment by MariuszFerdyn** [comment]
I am working on that: It is working on my test: https://squidproxy.northeurope.cloudapp.azure.com/ - I will implement it to the container also in the next version.
