### ISSUE TITLE
Build "Squid Cache" to act as a "reverse proxy" for "https://glasswallsolutions.com" (Local-Docker)

### ISSUE THREAD

**Issue by GINAGC** [filetrust/k8-reverse-proxy#3]
Configure a "[Squid Cache](http://www.squid-cache.org/)" instance to work as a "[Reverse Proxy](https://wiki.squid-cache.org/SquidFaq/ReverseProxy)" to serve the content of the website: https://glasswallsolutions.com

As part of this task:
- Provide SSL termination functionality (You may use self signed certificate for development).
- Delivery is to run it locally first as a docker container.
- Consider scripting the docker build image. so it might be initiated to serve a different website in a later stage.

As a functionality test, a typical client, Windows machine for instance should change the hosts file so that glasswallsolutions.com
host points to the docker container running the Squid image.

**Comment by MariuszFerdyn** [comment]
Done: https://github.com/filetrust/k8-reverse-proxy/pull/13
